version: "3.0"

services:
  postgres:
    image: postgres:18.0 
    container_name: custom-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_vol:/var/lib/postgresql
volumes:
  postgres_vol: