services:
  app:
    image: custom_nodejs
    container_name: custom_nodejs
    # environment:
    #   - PORT:${PORT:-3000}
    #   - NODE_ENV:${NODE_ENV:-dev}
    env_file:
    - ./nodejs/.env
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./nodejs:/app
      - /app/node_modules
    depends_on:
      - redis
  redis:
    image: redis
    container_name: app_redis
    ports:
      - "6379:6379"
    restart: always
